config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resources :sessions, only: %i[new create]
  resources :posts do
    member do
      get 'like'
      get 'dislike'
    end
    resources :comments
  end
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'
  get 'home/index'
  root 'home#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      redirect_to new_post_comments_path
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: @comment, url: post_comment_link do |form| %>
  <div class="mb-1">
    <%= form.label :message, class:"form-label" %>
    <%= form.text_field :message, class:"form-control" %>
  </div>
  <%= form.submit data:{ turbo_frame: "mainframe" }, class:"btn btn-primary"%>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "mainframe" do %>
  <div class="container">
    <h1>Edit Comment</h1>
    <%= render "form", {comment: @comment, post: @post , post_comment_link: post_comment_path(@post,@comment)} %>
  </div>
<% end %>

app/views/comments/index.html.erb
<div class="container text-center">
  <h2>Event Details</h2>
  <table class="table table-secondary mb-5">
    <tbody>
      <tr>
        <th scope="col">ID</th>
        <th scope="col"><%= @event.id %></th>
      </tr>
      <tr>
        <th scope="col">Owner Name</th>
        <th scope="col"><%= @event.owner_name %></th>
      </tr>
      <tr>
        <th scope="col">Name</th>
        <th scope="col"><%= @event.name %></th>
      </tr>
      <tr>
        <th scope="col">Description</th>
        <th scope="col"><%= @event.description %></th>
      </tr>
      <tr>
        <th scope="col">Event Date</th>
        <th scope="col"><%= @event.event_date %></th>
      </tr>
      <tr>
        <th scope="col">Category</th>
        <th scope="col"><%= @event.category.name %></th>
      </tr>
    </tbody>
  </table>
  <h2 class="text-center mb-5">Comments</h2>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Message</th>
        <th scope="col">Likes</th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.user.name  %></td>
          <td><%= comment.message %></td>
          <td><%= link_to "Like", add_like_path(comment), class:"btn btn-danger me-1" %><%= link_to "All Like", all_likes_path(comment), class:"btn btn-danger ml-1" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Add Comment", new_comment_path(@event), class: 'btn btn-primary'%>
</div>

app/views/comments/new.html.erb
<%= turbo_frame_tag "mainframe" do %>
  <div class="container">
    <h1>New Comment</h1>
    <%= render "form", {comment: @comment, post: @post , post_comment_link: post_comments_path(@post,@comment)} %>
  </div>
<% end %>